Repository theohbrothers/docker-code-server, pull requests merged in 2023-09, with the labels that each got.

#87 Refactor: Do not specify `ConvertFrom-Json -Depth` in `VARIANTS.ps1`
  generate/definitions/VARIANTS.ps1
Labels: refactor

#88 Enhancement (ci): Add `Update-Versions.ps1` and `cron` job
  .github/workflows/cron.yml
  README.md
  Update-Versions.ps1
  generate/definitions/FILES.ps1
  generate/templates/.github/workflows/cron.yml.ps1
  generate/templates/README.md.ps1
Labels: enhancement

#89 Enhancement (ci): Add `on: merge_group` for merge queue support
  .github/workflows/ci-master-pr.yml
  generate/templates/.github/workflows/ci-master-pr.yml.ps1
Labels: enhancement

#90 Refactor: Use tags instead of releases in `Update-Versions.ps1` to speed up script by avoiding pagination
  Update-Versions.ps1
Labels: refactor

#91 Fix: Preserve array when using `ConvertFrom-Json` in `VARIANTS.ps1`
  generate/definitions/VARIANTS.ps1
Labels: fix

#92 Refactor: Pipe to `ConvertFrom-Json` in `VARIANTS.ps1`
  generate/definitions/VARIANTS.ps1
Labels: refactor

#93 Enhancement (ci): Remove ` $env:GITHUB_TOKEN` in `Update-Versions.ps1`
  Update-Versions.ps1
Labels: enhancement

#94 Chore: Deprecate go 1.17, 1.18, and 1.19 variants
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/VARIANTS.ps1
Labels: chore

#95 Enhancement: Bump go variants to 1.20.8
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/VARIANTS.ps1
  variants/v4.8.3-docker-go-1.20.8-alpine-3.15/Dockerfile
  variants/v4.8.3-docker-go-1.20.8-alpine-3.15/docker-entrypoint.sh
  variants/v4.8.3-docker-go-1.20.8-alpine-3.15/settings.json
  variants/v4.8.3-docker-rootless-go-1.20.8-alpine-3.15/Dockerfile
  variants/v4.8.3-docker-rootless-go-1.20.8-alpine-3.15/docker-entrypoint.sh
  variants/v4.8.3-docker-rootless-go-1.20.8-alpine-3.15/settings.json
Labels: enhancement

#96 Refactor (ci): Use new `versions.json` config
  Update-Versions.ps1
  generate/definitions/VARIANTS.ps1
  generate/definitions/versions.json
Labels: refactor

#98 Enhancement (ci): Add `workflow_dispatch` to `cron` job
  .github/workflows/cron.yml
  generate/templates/.github/workflows/cron.yml.ps1
Labels: enhancement

#99 Refactor (ci): Build incremental variants using local docker cache instead of registry cache
  .github/workflows/ci-master-pr.yml
  .vscode/tasks.json
  generate/definitions/VARIANTS.ps1
  generate/templates/.github/workflows/ci-master-pr.yml.ps1
Labels: refactor

#100 Enhancement (ci): Add `go` to `versions.json`
  generate/definitions/VARIANTS.ps1
  generate/definitions/versions.json
Labels: enhancement

#102 Chore (ci): Remove unneeded `['_metadata']['base_tag']` from variant objects
  generate/definitions/VARIANTS.ps1
  generate/templates/docker-entrypoint.sh.ps1
Labels: chore

#105 Enhancement: Add code-server 4.17.1 variants
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/VARIANTS.ps1
  generate/definitions/versions.json
  generate/templates/Dockerfile.ps1
  variants/4.17.1-docker-go-1.20.8/Dockerfile
  variants/4.17.1-docker-go-1.20.8/docker-entrypoint.sh
  variants/4.17.1-docker-go-1.20.8/settings.json
  variants/4.17.1-docker-rootless-go-1.20.8/Dockerfile
  variants/4.17.1-docker-rootless-go-1.20.8/docker-entrypoint.sh
  variants/4.17.1-docker-rootless-go-1.20.8/settings.json
  variants/4.17.1-docker-rootless/Dockerfile
  variants/4.17.1-docker-rootless/docker-entrypoint.sh
  variants/4.17.1-docker-rootless/settings.json
  variants/4.17.1-docker/Dockerfile
  variants/4.17.1-docker/docker-entrypoint.sh
  variants/4.17.1-docker/settings.json
  variants/4.17.1/Dockerfile
  variants/4.17.1/docker-entrypoint.sh
  variants/4.17.1/settings.json
Labels: enhancement
